name: documentation
channels:
  - openeye
  - rdkit
  - omnia
  - psi4
  - bioconda
  - openbabel
dependencies:
# Base depends
  - python
  - pip
  - typing
  - scipy
  - numpy
  - numpydoc
  - pip:
    - nbsphinx
  #- forcebalance
  #- openmoltools
  #- openbabel
