name: documentation
channels:
  - omnia
  - conda-forge
  - default
dependencies:
# Base depends
  - python
  - pip
  - typing
  - scipy
  - numpy
  - numpydoc
  - nbsphinx
  - m2r
  #- forcebalance
  #- openmoltools
  #- openbabel
